### ISSUE TITLE
Public Path Vs Build path

### ISSUE THREAD

**Issue by smurugavel** [csabapalfi/html-webpack-uncss-plugin#1]
Hello.
my webpack build configuration has both public path and build path, they both are different. webpack production build has configuration to optimize css but html-webpack-uncss-plugin doesn't read css from build path. 

Error seems UnCSS is looking at C:\Src\"PublicPath"\vendor.css 
It should look at C:\"BuildPath"\vendor.css.

any suggestion?

Thanks
Vel

**Comment by csabapalfi** [comment]
At current time of writing this plugin only looks at embedded CSS (between `<style>` tags).

This is a pretty big limitation but it also keeps this code really simple. 

I'm happy to accept pull requests though.
